version: '3'
services:
  page:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - mysql
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__user: root
      database__connection__password: password
      database__connection__database: ghost
    networks:
      - my-network
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

networks:
  my-network: